spring.application.name=job-mvc
pebble.suffix=.peb.html
spring.datasource.url= jdbc:postgresql://localhost:5432/java-job
spring.datasource.username= postgres
spring.datasource.password= postgres
server.port=3000